# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: prelaunchr_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: prelaunchr_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql  
  encoding: unicode
  host: localhost
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: prelaunchr_production
  pool:     5
  username: postgres
  password: postgres
  template: template0